### PR TITLE
Feature/adapted struct jsonizer

### PR DESCRIPTION
**Pull request by daminetreg**
@linkineo and @dan-42 I would like to invite you to review my code here.

Please note that I've put the jsonizer in boost::fusion namespace, but this should be changed, I imagine to `pre::jsonize / pre::dejsonize` or something similar, please feel-free to propose.

The boost::fusion::for_each_member is something that I should take time to provide to boost officilially but for the moment lives in pre.

Thanks for your help.

Please also review : 
- https://github.com/daminetreg/lib-cpp-pre/blob/feature/adapted_struct_jsonizer/pre/boost/fusion/traits/is_container.hpp
- https://github.com/daminetreg/lib-cpp-pre/blob/feature/adapted_struct_jsonizer/pre/boost/fusion/traits/is_boost_variant.hpp

### CODE REVIEW

**Comment by linkineo** [comment]
DOC: you could add a reference to the Hunter cmake dependency, as this is might be required by any project using your lib, and hunter, while cool, is far from being mainstream yet.

**Comment by daminetreg** [comment]
Hunter shouldn't need any special treatment, but sure it makes sense to informe about it.

**Comment by linkineo** [comment]
Hunter seems to need a special treatment in as much as I need to conform to hunter's expectations (huntergate stuff etc) whenever I include the library in a project that is not using hunter yet, or am I wrong ?

**Comment by daminetreg** [comment]
Actually no the gate is taken for the build of pre and only the good things get installed on your system but you don't need to do anything specific. But I'll write some docs to explain how disabling it in case one don't want hunter to download the dependencies.

**Comment by linkineo** [comment]
It's not about downloading dependencies, which is cool, but about requiring people to adapt their cmakelist to use hunter, which could be a barrier to adoption.

**Comment by daminetreg** [comment]
there is no need for them to adapt their cmakelists.

**Comment by linkineo** [comment]
so I can add lib-pre as a submodule to my project, add it as a subdirectory in my cmakelist and just expect it to compile with no mention to hunter whatsoever ?. I tried, could not make it work. You got my git bundle by mail, maybe you'll see what I'm doing wrong.

**Comment by daminetreg** [comment]
Actually the project is thought to be added via find_package or via my patched hunter but not as git submodule via add_subdirectory. That's possibly why you are expecting errors as I didn't test the inclusion of the project this way and it's not the way normally one should use if he don't control the subproject. That's why hunter and cmake externalproject was invented.

**Comment by linkineo** [comment]
add_subdirectory may not be the best way to include dependencies, but it usually works without a hitch. anyway, would be cool to tell in the doc which ways you expect people to use your lib.

**Comment by daminetreg** [comment]
Yes I agree :smile: I'll anyway look that add_subdirectory works, but it looks like the problem you had is not because of this, it's because I wrongly referenced hunter that I in fact override locally in my build with -DHUNTER_SOURCE_DIR.

I did test it now that I fixed this, tell me if it works. Sorry for the problems.

**Comment by linkineo** [comment]
ok, so this time I went for the sysroot-style solution.
1) I compiled lib-pre, and installed it to a test syroot
2) I made a test app including your headers
-> Does not compile, as nlohmann-json headers are missing in the sysroot, when including adapted_struct_jsonize.hpp.
Your cmakelist does not seem to install the headers required, and nlohmann-json's cmakelist does not support make install.

**Comment by daminetreg** [comment]
Take this nlohmann-json : https://github.com/hunter-packages/json/blob/hunter/CMakeLists.txt The changes done to the CMakeLists are in an open pull-request to nlohmann.

Why don't you take a look at the unit-test ? And play with the lib from there for this review ?

**Comment by daminetreg** [comment]
Actually what you raise up with your test is a way of using hunter that is not supported, it's a deficiency actually, because hunter installs and compiles from it's own sysroot, but if you install then on your system then you don't get the dependent lib installed with, because it is thought that you integrate the lib with hunter again on your side. 

I'll think more to it, but I believe you discovered a missing feature in hunter that is : make install with hunter, but get all hunter dependencies also installed with in system for people don't wanting to use hunter to include lib-cpp-pre.

**Comment by daminetreg** [comment]
> Why don't you take a look at the unit-test ? And play with the lib from there for this review ?

I mean this because I'm more concerned with the implementation right now, than with the assets usability, which is something that needs to be done anyway, but where I didn't concentrate for the moment.

**Comment by linkineo** [comment]
Actually, I took your unit-test code and copied it to my test app. That's how I tried to compile the stuff and stumbled upon these issues. But fine, I'll have to either accept to use hunter or to play directly within your unit-test code. Still, I believe that a build system that is actually a closed ecosystem hinders adoption. You'll have my review comments concerning actual code by tomorrow evening.

**Comment by daminetreg** [comment]
> Still, I believe that a build system that is actually a closed ecosystem hinders adoption.

Totally agreeing but I wasn't focusing on this, because actually the code present here is not meant necessarily to stay in this lib, we could take it by express.o or anything else. Additionally perhaps it would make sense to embed a json parser of our invention, and supports different backend for the people for whom the json lib matters.

**Comment by daminetreg** [comment]
And actually you can still do the same as in the past : 
cd nlohmann/ && cmake -DHUNTER_ENABLED=off . && make install 
then cd lib-cpp-pre/ cmake -DHUNTER_ENABLED=off . && make install 

Then you can use it in your app.

**Comment by linkineo** [comment]
yep, but there is no install target in json/nlohmann's cmakelist ;-) but fine, I made it compile a while ago, the only thing being it shall work out of the box.

**Comment by daminetreg** [comment]
I told above I patched it, please take this nlohmann::json : https://github.com/hunter-packages/json  It is the same but with the good cmakelists

The Patch is awaiting merge from nlohmann : https://github.com/nlohmann/json/pull/123

**Pull request merged**
